[tool.black]
exclude = "tests/fixtures"
line-length = 100

[tool.mypy]
# strict = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "gi.repository.*"

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "src.*"

[tool.ruff]
builtins = ["__"]
cache-dir = "./.cache/.ruff"
exclude = ["tests/fixtures"]
fix = true
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN002", "ANN003", "D1"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
lines-after-imports = 2 # Ensures consistency for cases when there's variable vs function/class definitions after imports
lines-between-types = 1 # Separate import/from with 1 line
required-imports = ["from __future__ import annotations"]
